const expertises = [
    
    {
        expertiseName: "Acrobacias",
        attribute: "agi",
        info: "Você consegue fazer proezas acrobáticas.",
        id: "Iacrobacias",
    },
    {
        expertiseName: "Adestramento",
        attribute: "pre",
        info: "Você sabe lidar com animais.",
        id: "Iadestramento",
    },
    {
        expertiseName: "Artes",
        attribute: "pre",
        info: "Você sabe se expressar com diversas formas de arte, como música, dança, escrita, pintura, atuação entre outras.",
        id: "Iartes",
    },
    {
        expertiseName: "Atletismo",
        attribute: "for",
        info: "Você pode realizar façanhas atléticas.",
        id: "Iatletismo",
    },
    {
        expertiseName: "Atualidades",
        attribute: "int",
        info: "Você é um conhecedor de assuntos gerais, como política, esporte e entretenimento, e pode responder dúvidas relativas a esses assuntos.",
        id: "Iatualidades",
    },
    {
        expertiseName: "Ciências",
        attribute: "int",
        info: "Você estudou diversos campos científicos, como matemática, física, química e biologia, e pode responder dúvidas relativas a esses assuntos.",
        id: "Iciencias",
    },
    {
        expertiseName: "Crime",
        attribute: "agi",
        info: "Você sabe exercer atividades ilícitas",
        id: "Icrime",
    },
    {
        expertiseName: "Diplomacia",
        attribute: "pre",
        info: "Você convence pessoas com lábia e argumentação.",
        id: "Idiplomacia",
    },
    {
        expertiseName: "Enganação",
        attribute: "pre",
        info: "Você manipula pessoas com blefes e trapaças.",
        id: "Ienganacao",
    },
    {
        expertiseName: "Fortitude",
        attribute: "vig",
        info: "Você usa esta perícia para testes de resistência contra efeitos que exigem vitalidade, como doenças e venenos.",
        id: "Ifortitude",
    },
    {
        expertiseName: "Furtividade",
        attribute: "agi",
        info: "Você sabe ser discreto e sorrateiro.",
        id: "Ifurtividade",
    },
    {
        expertiseName: "Iniciativa",
        attribute: "agi",
        info: "Esta perícia determina sua velocidade de reação.",
        id: "Iiniciativa",
    },
    {
        expertiseName: "Intimidação",
        attribute: "pre",
        info: "Você pode assustar ou coagir outras pessoas.",
        id: "Iintimidacao",
    },
    {
        expertiseName: "Intuição",
        attribute: "int",
        info: "Esta perícia mede sua empatia e “sexto sentido”.",
        id: "Iintuicao",
    },
    {
        expertiseName: "Investigação",
        attribute: "int",
        info: "Você sabe como descobrir pistas e informações.",
        id: "Iinvestigacao",
    },
    {
        expertiseName: "Luta",
        attribute: "for",
        info: "Você usa Luta para fazer ataques corpo a corpo.",
        id: "Iluta",
    },
    {
        expertiseName: "Medicina",
        attribute: "int",
        info: "Você sabe tratar ferimentos, doenças e venenos.",
        id: "Imedicina",
    },
    {
        expertiseName: "Ocultismo",
        attribute: "int",
        info: "Você estudou o Paranormal.",
        id: "Iocultismo",
    },
    {
        expertiseName: "Percepção",
        attribute: "pre",
        info: "Você nota coisas usando os sentidos.",
        id: "Ipercepcao",
    },
    {
        expertiseName: "Pilotagem",
        attribute: "agi",
        info: "Você sabe operar veículos terrestres e aquáticos, como motos, carros e lanchas.",
        id: "Ipilotagem",
    },
    {
        expertiseName: "Pontaria",
        attribute: "agi",
        info: "Você usa Pontaria para fazer ataques à distância.",
        id: "Ipontaria",
    },
    {
        expertiseName: "Profissão",
        attribute: "int",
        info: "Você sabe exercer uma profissão específica, como advogado, engenheiro, jornalista ou publicitário.",
        id: "Iprofissao",
    },
    {
        expertiseName: "Reflexos",
        attribute: "agi",
        info: "Você usa esta perícia para testes de resistência contra efeitos que exigem reação rápida, como armadilhas e explosões.",
        id: "Ireflexos",
    },
    {
        expertiseName: "Religião",
        attribute: "pre",
        info: "Você possui conhecimento sobre teologia e as diversas religiões do mundo.",
        id: "Ireligiao",
    },
    {
        expertiseName: "Sobrevivência",
        attribute: "int",
        info: "Você pode se guiar em regiões selvagens e evitar perigos da natureza.",
        id: "Isobrevivencia",
    },
    {
        expertiseName: "Tática",
        attribute: "int",
        info: "Você recebeu educação militar.",
        id: "Itatica",
    },
    {
        expertiseName: "Tecnologia",
        attribute: "int",
        info: "Você possui conhecimentos avançados de eletrônica e informática.",
        id: "Itecnologia",
    },
    {
        expertiseName: "Vontade",
        attribute: "pre",
        info: "Você usa esta perícia para testes de resistência contra efeitos que exigem determinação, como intimidação e rituais que afetam a mente.",
        id: "Ivontade",
    },
];

export default expertises;
